### ISSUE TITLE
TestPlanAnalyzer: Failed read jmx file

### ISSUE THREAD

**Issue by QAInsights** [anthonygauthier/jmeter-live-changes-config#28]
@delirius325 I tried the latest version of Live Config element in 5.3 using OpenJDK 15. I am getting the below error. Please check.

```
2020-10-04 19:09:09,723 INFO o.a.j.s.SaveService: Loading file: C:\Tools\apache-jmeter-5.3\bin\null
2020-10-04 19:09:09,725 WARN o.j.r.p.TestPlanAnalyzer: Failed read jmx file
java.io.FileNotFoundException: C:\Tools\apache-jmeter-5.3\bin\null (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:211) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:153) ~[?:?]
	at org.jmeterplugins.repository.plugins.TestPlanAnalyzer.readBytesFromFile(TestPlanAnalyzer.java:64) [jmeter-plugins-manager-1.4.jar:?]
	at org.jmeterplugins.repository.plugins.TestPlanAnalyzer.getNodeListWithClassNames(TestPlanAnalyzer.java:103) [jmeter-plugins-manager-1.4.jar:?]
	at org.jmeterplugins.repository.plugins.TestPlanAnalyzer.analyze(TestPlanAnalyzer.java:33) [jmeter-plugins-manager-1.4.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.analyzeTestPlan(PluginSuggester.java:51) [jmeter-plugins-manager-1.4.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.findPluginsToInstall(PluginSuggester.java:44) [jmeter-plugins-manager-1.4.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.checkAndSuggest(PluginSuggester.java:28) [jmeter-plugins-manager-1.4.jar:?]
	at org.jmeterplugins.repository.logging.LoggerAppender.append(LoggerAppender.java:33) [jmeter-plugins-manager-1.4.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:543) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:485) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:460) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.Logger.log(Logger.java:161) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2198) [log4j-api-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2152) [log4j-api-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2135) [log4j-api-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2028) [log4j-api-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899) [log4j-api-2.13.1.jar:2.13.1]
	at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:184) [log4j-slf4j-impl-2.13.1.jar:2.13.1]
	at org.apache.jmeter.save.SaveService.loadTree(SaveService.java:427) [ApacheJMeter_core.jar:5.3]
	at io.github.delirius325.jmeter.config.livechanges.LiveChanges.startServer(LiveChanges.java:197) [jmeter.config.livechanges-0.1.0.jar:?]
	at io.github.delirius325.jmeter.config.livechanges.LiveChanges.testStarted(LiveChanges.java:58) [jmeter.config.livechanges-0.1.0.jar:?]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:205) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:380) [ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2020-10-04 19:09:09,725 WARN o.j.r.p.TestPlanAnalyzer: Cannot parse file: C:\Tools\apache-jmeter-5.3\bin\null
org.xml.sax.SAXParseException: Premature end of file.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source) ~[xercesImpl-2.12.0.jar:?]
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[xercesImpl-2.12.0.jar:?]
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122) ~[?:?]
	at org.jmeterplugins.repository.plugins.TestPlanAnalyzer.getNodeListWithClassNames(TestPlanAnalyzer.java:104) [jmeter-plugins-manager-1.4.jar:?]
	at org.jmeterplugins.repository.plugins.TestPlanAnalyzer.analyze(TestPlanAnalyzer.java:33) [jmeter-plugins-manager-1.4.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.analyzeTestPlan(PluginSuggester.java:51) [jmeter-plugins-manager-1.4.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.findPluginsToInstall(PluginSuggester.java:44) [jmeter-plugins-manager-1.4.jar:?]
	at org.jmeterplugins.repository.plugins.PluginSuggester.checkAndSuggest(PluginSuggester.java:28) [jmeter-plugins-manager-1.4.jar:?]
	at org.jmeterplugins.repository.logging.LoggerAppender.append(LoggerAppender.java:33) [jmeter-plugins-manager-1.4.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:543) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:485) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:460) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.core.Logger.log(Logger.java:161) [log4j-core-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2198) [log4j-api-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2152) [log4j-api-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2135) [log4j-api-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2028) [log4j-api-2.13.1.jar:2.13.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899) [log4j-api-2.13.1.jar:2.13.1]
	at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:184) [log4j-slf4j-impl-2.13.1.jar:2.13.1]
	at org.apache.jmeter.save.SaveService.loadTree(SaveService.java:427) [ApacheJMeter_core.jar:5.3]
	at io.github.delirius325.jmeter.config.livechanges.LiveChanges.startServer(LiveChanges.java:197) [jmeter.config.livechanges-0.1.0.jar:?]
	at io.github.delirius325.jmeter.config.livechanges.LiveChanges.testStarted(LiveChanges.java:58) [jmeter.config.livechanges-0.1.0.jar:?]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:205) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:380) [ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2020-10-04 19:09:09,734 ERROR i.g.d.j.c.l.LiveChanges: LiveChanges was unable to load the test plan tree. More info in JMeter's console.
2020-10-04 19:09:09,747 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2020-10-04 19:09:09,754 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2020-10-04 19:09:09,754 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2020-10-04 19:09:09,754 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2020-10-04 19:09:09,754 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2020-10-04 19:09:09,755 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2020-10-04 19:09:09,755 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2020-10-04 19:09:09,755 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2020-10-04 19:09:14,205 INFO o.a.j.g.a.Start: Stopping test
2020-10-04 19:09:14,224 INFO o.a.j.t.JMeterThread: Stopping: Thread Group 1-1
2020-10-04 19:09:14,224 WARN o.a.j.t.JMeterThread: Interrupting: Thread Group 1-1 sampler: HTTP Request
2020-10-04 19:09:14,225 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2020-10-04 19:09:14,226 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2020-10-04 19:09:14,226 ERROR i.g.d.j.c.l.LiveChanges: LiveChanges was unable to correctly shutdown Jetty server. More info in JMeter's console
java.lang.NullPointerException: Cannot invoke "io.github.delirius325.jmeter.config.livechanges.api.App.stop()" because "this.app" is null
	at io.github.delirius325.jmeter.config.livechanges.LiveChanges.finalizeTest(LiveChanges.java:213) [jmeter.config.livechanges-0.1.0.jar:?]
	at io.github.delirius325.jmeter.config.livechanges.LiveChanges.testEnded(LiveChanges.java:74) [jmeter.config.livechanges-0.1.0.jar:?]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:217) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:491) [ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2020-10-04 19:09:14,226 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)


```

**Comment by anthonygauthier** [comment]
@QAInsights FYI, I will look into what happens with the latest JDK. I've been getting the itch to start working on this again.

**Comment by anthonygauthier** [comment]
Closing as `master` was tested with the latest version of Java (21) and there are no problems related to reading the `jmx` file.
